### ISSUE TITLE
[Android] Switching view causing the App to crash

### ISSUE THREAD

**Issue by eyeveye** [AndreiMisiukevich/CardView.MAUI#37]
If you have imagebuttons to navigate the carouselview, and if switch (clicking the imagebutton) different view, it will crash the application.

It occurs when a view is added to a ViewGroup (e.g., Grid, StackLayout) but hasn't been properly removed from its current parent before being added again, hence the IllegalStateException.

From the stack trace, it is related PanCardView (as mentioned in the stack trace: at PanCardView.CardsView.PrepareView and PanCardView.CardsView.InitViews). This indicates that the view is being added to the view hierarchy multiple times or without proper removal, likely due to the PanCardView library.

Here is the error:

{Java.Lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 20830
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 75
   at Android.Views.ViewGroup.AddView(View child) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.ViewGroup.cs:line 2148
   at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler) in /_/src/Core/src/Handlers/ContentView/ContentViewHandler.Android.cs:line 42
   at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page) in /_/src/Core/src/Handlers/ContentView/ContentViewHandler.Android.cs:line 47
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in /_/src/Core/src/PropertyMapper.cs:line 172
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in /_/src/Core/src/PropertyMapper.cs:line 47
   at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property) in /_/src/Core/src/PropertyMapper.cs:line 72
   at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property) in /_/src/Core/src/Handlers/Element/ElementHandler.cs:line 87
   at Microsoft.Maui.Controls.Element.UpdateHandlerValue(String property) in /_/src/Controls/src/Core/Element/Element.cs:line 649
   at Microsoft.Maui.Controls.VisualElement.UpdateHandlerValue(String property) in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1955
   at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName) in /_/src/Controls/src/Core/Element/Element.cs:line 636
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in /_/src/Controls/src/Core/BindableObject.cs:line 642
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindableObject.cs:line 569
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindingExpression.cs:line 163
   at Microsoft.Maui.Controls.BindingExpression.Apply(Object sourceObject, BindableObject target, BindableProperty property, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindingExpression.cs:line 78
   at Microsoft.Maui.Controls.Binding.Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged, SetterSpecificity specificity) in /_/src/Controls/src/Core/Binding.cs:line 137
   at Microsoft.Maui.Controls.BindableObject.ApplyBindings(Boolean skipBindingContext, Boolean fromBindingContextChanged) in /_/src/Controls/src/Core/BindableObject.cs:line 665
   at Microsoft.Maui.Controls.BindableObject.BindingContextPropertyChanged(BindableObject bindable, Object oldvalue, Object newvalue) in /_/src/Controls/src/Core/BindableObject.cs:line 684
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in /_/src/Controls/src/Core/BindableObject.cs:line 644
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindableObject.cs:line 569
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value) in /_/src/Controls/src/Core/BindableObject.cs:line 474
   at Microsoft.Maui.Controls.BindableObject.set_BindingContext(Object value) in /_/src/Controls/src/Core/BindableObject.cs:line 54
   at PanCardView.CardsView.PrepareView(IEnumerable`1 bookedViews, Int32 index)
   at PanCardView.CardsView.InitViews(Boolean isFront, AnimationDirection animationDirection, IEnumerable`1 bookedViews, Int32[] indices)
   at PanCardView.CardsView.SetupNextView(Int32 index, IEnumerable`1 bookedViews)
   at PanCardView.CardsView.SetupBackViews(Nullable`1 index)
   at PanCardView.CardsView.TryAutoNavigate()
   at PanCardView.CardsView.ForceRedrawViews()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
   at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 37
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Lang.IRunnable.cs:line 84
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
  --- End of managed Java.Lang.IllegalStateException stack trace ---
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5275)
	at android.view.ViewGroup.addView(ViewGroup.java:5104)
	at android.view.ViewGroup.addView(ViewGroup.java:5044)
	at android.view.ViewGroup.addView(ViewGroup.java:5016)
	at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
	at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:31)
	at android.view.View.performClick(View.java:7659)
	at android.view.View.performClickInternal(View.java:7636)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30156)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

  --- End of managed Java.Lang.IllegalStateException stack trace ---
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5275)
	at android.view.ViewGroup.addView(ViewGroup.java:5104)
	at android.view.ViewGroup.addView(ViewGroup.java:5044)
	at android.view.ViewGroup.addView(ViewGroup.java:5016)
	at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
	at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:31)
	at android.view.View.performClick(View.java:7659)
	at android.view.View.performClickInternal(View.java:7636)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30156)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
}

**Comment by DashTheDev** [comment]
Hey @eyeveye! I had a quick play to try replicate this (to no avail), I think this is a very specific issue.

Would you be able to provide at minimum some XAML/code examples of the scenario you're describing and if possible, could you please provide a minimal reproduceable project? Thanks!

**Comment by eyeveye** [comment]
> Hey @eyeveye! I had a quick play to try replicate this (to no avail), I think this is a pretty specific issue to your scenario.
> 
> Would you be able to provide at minimum some XAML/code examples of the scenario you're describing and if possible, could you please provide a minimal reproduceable project? Thanks!

Hi, thanks for the reply. I have created a minimal reproduceable project. 
https://github.com/eyeveye/PanCard

**Comment by DashTheDev** [comment]
Thanks so much! I'll take a look and hopefully produce a fix when I can after work 😀

**Comment by DashTheDev** [comment]
Just an update on this one. Still looking into fixing this, it seems to have something to do with the speed in which tabs are switched. I'm still yet to create other scenarios based off this one, to further deduce if it's specific to this exact setup or data templated views as a whole (as it doesn't struggle with a static array of views). Either way, I'll keep figuring it out.

In the meantime, if you want to the prevent the crashes set `IsViewReusingEnabled = false;` on the `CarouselView`. It's not ideal at all, as it means it will create a new instance of the view every time a tab is clicked rather than displaying the first created instance, but for now it will prevent crashing (or at least it did for me) until I can further explore this issue.

**Comment by DashTheDev** [comment]
I've had a bit more of a play with this @eyeveye. I've come to the conclusion that the crash is **very** specific to your implementation. The way that you've setup the `ItemsSource` as a collection of `Views` and then you have an `ItemTemplate` that has a `ContentView` with content bound by the provided `BindingContext` is something that MAUI doesn't like at all.

Ultimately, I don't know exactly why MAUI doesn't like it, but I can imagine have so many nested `ContentViews` or `Views` in general probably makes it harder for the renderer. I can dig deeper, but I don't really want to spend the time doing so when there are alternatives.

I can offer you two solutions with your exact setup here. These don't crash upon my testing, but the original does:

### Drop ItemTemplate
You don't need to specify the `ItemTemplate` as the `ItemSource` you provide is a collection of `Views` and you don't need to bind anything from them inside the template.

```XAML
<cards:CarouselView
    x:Name="cvPage"
    HorizontalOptions="FillAndExpand"
    IsAutoNavigatingAnimationEnabled="True"
    IsCyclical="False"
    ItemsSource="{Binding ViewDV}"
    SelectedIndex="{Binding SelectedViewModelIndex, Mode=TwoWay}"
    VerticalOptions="FillAndExpand" />
```

### Use a static ItemsSource
Since in this example, you don't require the `ItemsSource`/view collection to be dynamic. You can provide it statically in the XAML. You'll also need to make sure you set `SelectedViewModelIndex = 0;` instead of `-1` in your ViewModel otherwise the first slide won't display on load.

```XAML
<cards:CarouselView
    x:Name="cvPage"
    HorizontalOptions="FillAndExpand"
    IsAutoNavigatingAnimationEnabled="True"
    IsCyclical="False"
    SelectedIndex="{Binding SelectedViewModelIndex, Mode=TwoWay}"
    VerticalOptions="FillAndExpand">
    <cards:CarouselView.ItemsSource>
        <x:Array Type="{x:Type View}">
            <v:cv1 />
            <v:cv2 />
            <v:cv1 />
            <v:cv2 />
        </x:Array>
    </cards:CarouselView.ItemsSource>
</cards:CarouselView>
```

### Conclusion
This is the sucker that is causing you problems, MAUI does not like the nested `ContentViews` with the `Content` binding inside a `DataTemplate`.

```XAML
<cards:CarouselView.ItemTemplate>
    <DataTemplate>
        <ContentView Content="{Binding}" />
    </DataTemplate>
</cards:CarouselView.ItemTemplate>
```

Let me know if the above solutions work for you! 😄

**Comment by eyeveye** [comment]
> I've had a bit more of a play with this @eyeveye. I've come to the conclusion that the crash is **very** specific to your implementation. The way that you've setup the `ItemsSource` as a collection of `Views` and then you have an `ItemTemplate` that has a `ContentView` with content bound by the provided `BindingContext` is something that the `CarouselView` doesn't account for (and never will).
> 
> Ultimately, I think this is because when the `BindingContext` is being set for the `ContentView` that is created by the `ItemTemplate`, the `Content` (otherwise known as your bound `Views`) is being added to the parent `ContentView`. Since there's this extra `ContentView` layer, the `View` itself is never removed from the original parent `ContentView`. And so, when the `BindingContext` is changed again and set to that same `View`, the `View` is added again without having been removed which causes the error. Hard to explain well, but it's due to the extra nested `ContentView` that you've setup that our `CarouselView` isn't handling the add/remove of children properly. So, if we simplify the implementation and leave the `CarouselView` to do its thing, then it's all fixed.
> 
> I can offer you two solutions with your exact setup here. These don't crash upon my testing, but the original does:
> 
> ### Drop ItemTemplate
> You don't need to specify the `ItemTemplate` as the `ItemSource` you provide is a collection of `Views` and you don't need to bind anything from them inside the template.
> 
> ```
> <cards:CarouselView
>     x:Name="cvPage"
>     HorizontalOptions="FillAndExpand"
>     IsAutoNavigatingAnimationEnabled="True"
>     IsCyclical="False"
>     ItemsSource="{Binding ViewDV}"
>     SelectedIndex="{Binding SelectedViewModelIndex, Mode=TwoWay}"
>     VerticalOptions="FillAndExpand" />
> ```
> 
> ### Use a static ItemsSource
> Since in this example, you don't require the `ItemsSource`/view collection to be dynamic. You can provide it statically in the XAML. You'll also need to make sure you set `SelectedViewModelIndex = 0;` instead of `-1` in your ViewModel otherwise the first slide won't display on load.
> 
> ```
> <cards:CarouselView
>     x:Name="cvPage"
>     HorizontalOptions="FillAndExpand"
>     IsAutoNavigatingAnimationEnabled="True"
>     IsCyclical="False"
>     SelectedIndex="{Binding SelectedViewModelIndex, Mode=TwoWay}"
>     VerticalOptions="FillAndExpand">
>     <cards:CarouselView.ItemsSource>
>         <x:Array Type="{x:Type View}">
>             <v:cv1 />
>             <v:cv2 />
>             <v:cv1 />
>             <v:cv2 />
>         </x:Array>
>     </cards:CarouselView.ItemsSource>
> </cards:CarouselView>
> ```
> 
> ### Conclusion
> This is the sucker that is causing you problems, `CarouselView` does not have full control over child add/remove with the nested `ContentViews` inside a `DataTemplate`. And yes, I have ensured that using a `DataTemplate` in general does not cause this crash, only this specific `DataTemplate` implementation does.
> 
> ```
> <cards:CarouselView.ItemTemplate>
>     <DataTemplate>
>         <ContentView Content="{Binding}" />
>     </DataTemplate>
> </cards:CarouselView.ItemTemplate>
> ```
> 
> Let me know if the above solutions work for you! 😄

Thanks for the help! I removed the <DataTemplate> part, and it is no longer crashed.
Thanks again.

**Comment by AndreiMisiukevich** [comment]
@DashTheDev, why are you so freaking cool, man? <3
